(function(){
    var info = {
        container:'jsmind_container',       // [必选] 容器的ID
        editable:true,                      // [可选] 是否启用编辑
        theme:'primary',                     // [可选] 主题

    };
    var data = {
        /* 元数据，定义思维导图的名称、作者、版本等信息 */
        "meta":{
            "name":"高级前端知识体系思维脑图",
            "author":"401814074@qq.com",
            "version":"1.0.0"
        },
        /* 数据格式声明 */
        "format":"node_array",
        /* 数据内容 */
        "data":[
            {"id":"root", "isroot":true, "topic":"高级前端知识体系"},
            /* 结构目录 */
            {"id":"list-1", "parentid":"root", "topic":"html"},
            {"id":"list-2", "parentid":"root", "topic":"css"},
            {"id":"list-3", "parentid":"root", "topic":"javascript"},
            {"id":"list-4", "parentid":"root", "topic":"html5"},
            {"id":"list-5", "parentid":"root", "topic":"web前端工程师职业路径"},
            {"id":"list-6", "parentid":"root", "topic":"h5游戏工程师"},
            {"id":"list-7", "parentid":"root", "topic":"windows&linux基础"},
            {"id":"list-8", "parentid":"root", "topic":"后端语言"},
            {"id":"list-9", "parentid":"root", "topic":"http协议"},
            {"id":"list-10", "parentid":"root", "topic":"前端的明天"},
            /* html */
            {"id":"list-1-1", "parentid":"list-1", "topic":"html简介和发展历史"},
            {"id":"list-1-2", "parentid":"list-1", "topic":"基础dtd和meta"},
            {"id":"list-1-3", "parentid":"list-1", "topic":"html元素及属性"},
            {"id":"list-1-4", "parentid":"list-1", "topic":"html语义化和seo"},
            {"id":"list-1-5", "parentid":"list-1", "topic":"html媒体"},
            {"id":"list-1-6", "parentid":"list-1", "topic":"html常见颜色名"},
            {"id":"list-1-7", "parentid":"list-1", "topic":"常见面试题"},
                /* html元素及属性 */
                {"id":"list-1-3-1", "parentid":"list-1-3", "topic":"块级元素"},
                {"id":"list-1-3-2", "parentid":"list-1-3", "topic":"行类元素"},
                    /* 块级元素 */
                    {"id":"list-1-3-1-1", "parentid":"list-1-3-1", "topic":"div"},
                    {"id":"list-1-3-1-2", "parentid":"list-1-3-1", "topic":"table"},
                    {"id":"list-1-3-1-3", "parentid":"list-1-3-1", "topic":"p"},
                    {"id":"list-1-3-1-4", "parentid":"list-1-3-1", "topic":"h1-h6"},
                    {"id":"list-1-3-1-5", "parentid":"list-1-3-1", "topic":"iframe"},
                    {"id":"list-1-3-1-6", "parentid":"list-1-3-1", "topic":"dl、ul、ol"},
                    {"id":"list-1-3-1-7", "parentid":"list-1-3-2", "topic":"form"},
                    /* 行类元素 */
                    {"id":"list-1-3-2-1", "parentid":"list-1-3-2", "topic":"a"},
                    {"id":"list-1-3-2-2", "parentid":"list-1-3-2", "topic":"img"},
                    {"id":"list-1-3-2-3", "parentid":"list-1-3-2", "topic":"em、strong"},
                    {"id":"list-1-3-2-4", "parentid":"list-1-3-2", "topic":"span"},
                    {"id":"list-1-3-2-5", "parentid":"list-1-3-2", "topic":"sub、sup"},
                    {"id":"list-1-3-2-6", "parentid":"list-1-3-2", "topic":"form内元素"},
            /* css */
            {"id":"list-2-1", "parentid":"list-2", "topic":"选择器"},
            {"id":"list-2-2", "parentid":"list-2", "topic":"css核心知识点"},
            {"id":"list-2-3", "parentid":"list-2", "topic":"css基本样式"},
            {"id":"list-2-4", "parentid":"list-2", "topic":"css盒子模拟"},
            {"id":"list-2-5", "parentid":"list-2", "topic":"常用布局"},
            {"id":"list-2-6", "parentid":"list-2", "topic":"css hack"},
                /* 选择器 */
                {"id":"list-2-1-1", "parentid":"list-2-1", "topic":"id选择器"},
                {"id":"list-2-1-2", "parentid":"list-2-1", "topic":"类选择器"},
                {"id":"list-2-1-3", "parentid":"list-2-1", "topic":"派生选择器"},
                {"id":"list-2-1-4", "parentid":"list-2-1", "topic":"属性选择器"},
                {"id":"list-2-1-5", "parentid":"list-2-1", "topic":"后代选择器"},
                {"id":"list-2-1-6", "parentid":"list-2-1", "topic":"相邻兄弟选择器"},
                {"id":"list-2-1-7", "parentid":"list-2-1", "topic":"子类元素选择器"},
                {"id":"list-2-1-8", "parentid":"list-2-1", "topic":"伪选择器"},
                {"id":"list-2-1-9", "parentid":"list-2-1", "topic":"选择器优先级计算公式"},
                /* css核心知识点 */
                {"id":"list-2-2-1", "parentid":"list-2-2", "topic":"浮动float"},
                {"id":"list-2-2-2", "parentid":"list-2-2", "topic":"位子position"},
                {"id":"list-2-2-3", "parentid":"list-2-2", "topic":"行高line-height"},
                {"id":"list-2-2-4", "parentid":"list-2-2", "topic":"等高div"},
                {"id":"list-2-2-5", "parentid":"list-2-2", "topic":"透明opacity"},
                {"id":"list-2-2-6", "parentid":"list-2-2", "topic":"1px的table"},
                {"id":"list-2-2-7", "parentid":"list-2-2", "topic":"锤子水平居中"},
                {"id":"list-2-2-8", "parentid":"list-2-2", "topic":"透明和滤镜"},
                /* css基本样式 */
                {"id":"list-2-3-1", "parentid":"list-2-3", "topic":"背景"},
                {"id":"list-2-3-2", "parentid":"list-2-3", "topic":"边框"},
                {"id":"list-2-3-3", "parentid":"list-2-3", "topic":"文本"},
                {"id":"list-2-3-4", "parentid":"list-2-3", "topic":"字体"},
                {"id":"list-2-3-5", "parentid":"list-2-3", "topic":"连接"},
                {"id":"list-2-3-6", "parentid":"list-2-3", "topic":"表格"},
                {"id":"list-2-3-7", "parentid":"list-2-3", "topic":"轮廓"},
                /* css盒子模型 */
                {"id":"list-2-4-1", "parentid":"list-2-4", "topic":"标准盒子模型"},
                {"id":"list-2-4-2", "parentid":"list-2-4", "topic":"怪异盒子模型"},
                /* 常用布局 */
                {"id":"list-2-5-1", "parentid":"list-2-5", "topic":"一列布局"},
                {"id":"list-2-5-2", "parentid":"list-2-5", "topic":"二列布局"},
                {"id":"list-2-5-3", "parentid":"list-2-5", "topic":"三列布局"},
                {"id":"list-2-5-4", "parentid":"list-2-5", "topic":"多列布局"},
                {"id":"list-2-5-5", "parentid":"list-2-5", "topic":"流式布局"},
                {"id":"list-2-5-6", "parentid":"list-2-5", "topic":"双飞翼布局"},
            /* javascript */
            {"id":"list-3-1", "parentid":"list-3", "topic":"javascript发展史"},
            {"id":"list-3-2", "parentid":"list-3", "topic":"html中引用"},
            {"id":"list-3-3", "parentid":"list-3", "topic":"语言基础"},
            {"id":"list-3-4", "parentid":"list-3", "topic":"变量作用域和内存"},
            {"id":"list-3-5", "parentid":"list-3", "topic":"地址和按值引用类型"},
            {"id":"list-3-6", "parentid":"list-3", "topic":"面向对象的oop"},
            {"id":"list-3-7", "parentid":"list-3", "topic":"函数深入"},
            {"id":"list-3-8", "parentid":"list-3", "topic":"DOM和DOM事件"},
            {"id":"list-3-9", "parentid":"list-3", "topic":"BOM"},
            {"id":"list-3-10", "parentid":"list-3", "topic":"正则表达式"},
            {"id":"list-3-11", "parentid":"list-3", "topic":"form操作"},
            {"id":"list-3-12", "parentid":"list-3", "topic":"错误以及调试"},
            {"id":"list-3-13", "parentid":"list-3", "topic":"高级技巧"},
            {"id":"list-3-14", "parentid":"list-3", "topic":"常见面试题"},
            /* html5 */
            {"id":"list-4-1", "parentid":"list-4", "topic":"html5"},
            {"id":"list-4-2", "parentid":"list-4", "topic":"css3"},
            {"id":"list-4-3", "parentid":"list-4", "topic":"ECMAScript5"},
            {"id":"list-4-4", "parentid":"list-4", "topic":"老式浏览器如何应用新变化"},
                /* html5 */
                {"id":"list-4-1-1", "parentid":"list-4-1", "topic":"推出的理由和目标"},
                {"id":"list-4-1-2", "parentid":"list-4-1", "topic":"html5和html4区别"},
                {"id":"list-4-1-3", "parentid":"list-4-1", "topic":"全局属性spellcheck等"},
                {"id":"list-4-1-4", "parentid":"list-4-1", "topic":"编辑API"},
                {"id":"list-4-1-5", "parentid":"list-4-1", "topic":"canvas"},
                {"id":"list-4-1-6", "parentid":"list-4-1", "topic":"history api"},
                {"id":"list-4-1-7", "parentid":"list-4-1", "topic":"存储"},
                {"id":"list-4-1-8", "parentid":"list-4-1", "topic":"文件API(上传和下载)"},
                {"id":"list-4-1-9", "parentid":"list-4-1", "topic":"通信API(摆脱传统轮询的新API)"},
                {"id":"list-4-1-10", "parentid":"list-4-1", "topic":"XMLHttpRequset"},
                {"id":"list-4-1-11", "parentid":"list-4-1", "topic":"多线程"},
                {"id":"list-4-1-12", "parentid":"list-4-1", "topic":"html5定位"},
                {"id":"list-4-1-13", "parentid":"list-4-1", "topic":"媒体相关API"},
                {"id":"list-4-1-14", "parentid":"list-4-1", "topic":"其他API"},
                    /* html5和html4区别 */
                    {"id":"list-4-1-2-1", "parentid":"list-4-1-2", "topic":"新增和废气的元素"},
                    {"id":"list-4-1-2-2", "parentid":"list-4-1-2", "topic":"对原元素的改良(表单和iframe)"},
                    /* canvas */
                    {"id":"list-4-1-5-1", "parentid":"list-4-1-5", "topic":"与svgh和vml之间的差异"},
                    {"id":"list-4-1-5-2", "parentid":"list-4-1-5", "topic":"贝塞尔曲线()"},
                    {"id":"list-4-1-5-3", "parentid":"list-4-1-5", "topic":"绘图的方法(路径，矩形，圆圈，渐变)"},
                    {"id":"list-4-1-5-4", "parentid":"list-4-1-5", "topic":"图像处理的方法drawimage等"},
                    {"id":"list-4-1-5-5", "parentid":"list-4-1-5", "topic":"canvas动画效果"},
                    {"id":"list-4-1-5-6", "parentid":"list-4-1-5", "topic":"像素处理(复古效果)"},
                    {"id":"list-4-1-5-7", "parentid":"list-4-1-5", "topic":"canvas的3d渲染webGL"},
                    {"id":"list-4-1-5-8", "parentid":"list-4-1-5", "topic":"canvas开发2d游戏"},
                    /* html5定位 */
                    {"id":"list-4-1-12-1", "parentid":"list-4-1-12", "topic":"利用H5实现定位并进行逆向地址解析"},
                    {"id":"list-4-1-12-2", "parentid":"list-4-1-12", "topic":"监听用户的位置"},
                    {"id":"list-4-1-12-3", "parentid":"list-4-1-12", "topic":"在自己页面中使用百度地图"},
                    /* 其他API */
                    {"id":"list-4-1-14-1", "parentid":"list-4-1-14", "topic":"visibilly的新增Api比较原有jQuery操作方法"},
                    {"id":"list-4-1-14-2", "parentid":"list-4-1-14", "topic":"全屏fullScreen api比较原全屏的优点缺点"},
                    {"id":"list-4-1-14-3", "parentid":"list-4-1-14", "topic":"拖放api和原有jQuery拖放API的优点缺点"},
            /* web前端工程师职业路径 */
            {"id":"list-5-1", "parentid":"list-5", "topic":"常见的设计模式"},
            {"id":"list-5-2", "parentid":"list-5", "topic":"和美工配合的事"},
            {"id":"list-5-3", "parentid":"list-5", "topic":"常用的库"},
            {"id":"list-5-4", "parentid":"list-5", "topic":"css在工程中开发的变化"},
            {"id":"list-5-5", "parentid":"list-5", "topic":"性能优化"},
            {"id":"list-5-6", "parentid":"list-5", "topic":"数据结构的概述"},
            {"id":"list-5-7", "parentid":"list-5", "topic":"常用算法"},
            {"id":"list-5-8", "parentid":"list-5", "topic":"代码版本库"},
            {"id":"list-5-9", "parentid":"list-5", "topic":"结合php"},
            {"id":"list-5-10", "parentid":"list-5", "topic":"结合nodejs"},
            {"id":"list-5-11", "parentid":"list-5", "topic":"结合java"},
            {"id":"list-5-12", "parentid":"list-5", "topic":"项目的构建与部署"},
            {"id":"list-5-13", "parentid":"list-5", "topic":"h5的移动开发"},
            {"id":"list-5-14", "parentid":"list-5", "topic":"web前端黑客入门"},
            {"id":"list-5-15", "parentid":"list-5", "topic":"webapp"},
                /* 常见的设计模式 */
                {"id":"list-5-1-1", "parentid":"list-5-1", "topic":"单例模式"},
                {"id":"list-5-1-2", "parentid":"list-5-1", "topic":"构造模式"},
                {"id":"list-5-1-3", "parentid":"list-5-1", "topic":"建造者模式"},
                {"id":"list-5-1-4", "parentid":"list-5-1", "topic":"工厂模式"},
                {"id":"list-5-1-5", "parentid":"list-5-1", "topic":"装饰柱模式"},
                {"id":"list-5-1-6", "parentid":"list-5-1", "topic":"外观模式"},
                {"id":"list-5-1-7", "parentid":"list-5-1", "topic":"代理模式"},
                {"id":"list-5-1-8", "parentid":"list-5-1", "topic":"观察者模式"},
                {"id":"list-5-1-9", "parentid":"list-5-1", "topic":"命令模式"},
                {"id":"list-5-1-10", "parentid":"list-5-1", "topic":"迭代模式"},
                {"id":"list-5-1-11", "parentid":"list-5-1", "topic":"享元模式"},
                {"id":"list-5-1-12", "parentid":"list-5-1", "topic":"责任链模式"},
                {"id":"list-5-1-13", "parentid":"list-5-1", "topic":"适配器式"},
                {"id":"list-5-1-14", "parentid":"list-5-1", "topic":"组合模式"},
                {"id":"list-5-1-15", "parentid":"list-5-1", "topic":"模板模式"},
                {"id":"list-5-1-16", "parentid":"list-5-1", "topic":"中介者模式"},
                {"id":"list-5-1-17", "parentid":"list-5-1", "topic":"状态模式"},
                {"id":"list-5-1-18", "parentid":"list-5-1", "topic":"桥接模式"},
                /* 和美工配合的事 */
                {"id":"list-5-2-1", "parentid":"list-5-2", "topic":""},
                /* 常用的库 */
                {"id":"list-5-3-1", "parentid":"list-5-3", "topic":"操作DOM以及请求"},
                {"id":"list-5-3-2", "parentid":"list-5-3", "topic":"mvc和mvvm"},
                {"id":"list-5-3-3", "parentid":"list-5-3", "topic":"图表"},
                {"id":"list-5-3-4", "parentid":"list-5-3", "topic":"动画"},
                {"id":"list-5-3-5", "parentid":"list-5-3", "topic":"ui组件"},
                    /* 操作DOM以及请求 */
                    {"id":"list-5-3-1-1", "parentid":"list-5-3-1", "topic":"jQuery"},
                    {"id":"list-5-3-1-2", "parentid":"list-5-3-1", "topic":"zepto"},
                    /* mvc和mvvm */
                    {"id":"list-5-3-2-1", "parentid":"list-5-3-2", "topic":"mvc和mvvm基本概念"},
                    {"id":"list-5-3-2-2", "parentid":"list-5-3-2", "topic":"backone"},
                    {"id":"list-5-3-2-3", "parentid":"list-5-3-2", "topic":"canjs"},
                    {"id":"list-5-3-2-4", "parentid":"list-5-3-2", "topic":"spinejs"},
                    {"id":"list-5-3-2-5", "parentid":"list-5-3-2", "topic":"angularjs"},
                    {"id":"list-5-3-2-6", "parentid":"list-5-3-2", "topic":"knockout"},
                    {"id":"list-5-3-2-7", "parentid":"list-5-3-2", "topic":"react"},
                    {"id":"list-5-3-2-8", "parentid":"list-5-3-2", "topic":"polymer"},
                    /* 图表 */
                    {"id":"list-5-3-3-1", "parentid":"list-5-3-3", "topic":"highcharts"},
                    {"id":"list-5-3-3-2", "parentid":"list-5-3-3", "topic":"raphael"},
                    {"id":"list-5-3-3-3", "parentid":"list-5-3-3", "topic":"d3js"},
                    {"id":"list-5-3-3-4", "parentid":"list-5-3-3", "topic":"icharts"},
                    {"id":"list-5-3-3-5", "parentid":"list-5-3-3", "topic":"functionCharts"},
                    /* 动画 */
                    {"id":"list-5-3-4-1", "parentid":"list-5-3-4", "topic":"jquery transit"},
                    {"id":"list-5-3-4-2", "parentid":"list-5-3-4", "topic":"transfrom.js"},
                    {"id":"list-5-3-4-3", "parentid":"list-5-3-4", "topic":"pager.js"},
                    {"id":"list-5-3-4-4", "parentid":"list-5-3-4", "topic":"move.js"},
                    {"id":"list-5-3-4-5", "parentid":"list-5-3-4", "topic":"animatable"},
                    {"id":"list-5-3-4-6", "parentid":"list-5-3-4", "topic":"scripty2"},
                    {"id":"list-5-3-4-7", "parentid":"list-5-3-4", "topic":"jquery ui"},
                    {"id":"list-5-3-4-8", "parentid":"list-5-3-4", "topic":"animate.css"},
                    /* ui组件 */
                    {"id":"list-5-3-5-1", "parentid":"list-5-3-5", "topic":"jqueryui"},
                    {"id":"list-5-3-5-2", "parentid":"list-5-3-5", "topic":"extjs"},
                /* css在工程中开发的变化 */
                {"id":"list-5-4-1", "parentid":"list-5-4", "topic":"less"},
                {"id":"list-5-4-2", "parentid":"list-5-4", "topic":"sass"},
                {"id":"list-5-4-3", "parentid":"list-5-4", "topic":"css oo"},
                /* 性能优化 */
                {"id":"list-5-5-1", "parentid":"list-5-5", "topic":"雅虎军规详解与实战"},
                {"id":"list-5-5-2", "parentid":"list-5-5", "topic":"移动端webapp性能优化"},
                /* 数据结构的概述 */
                {"id":"list-5-6-1", "parentid":"list-5-6", "topic":""},
                /* 常用算法 */
                {"id":"list-5-7-1", "parentid":"list-5-7", "topic":"冒泡排序"},
                {"id":"list-5-7-2", "parentid":"list-5-7", "topic":"插入排序"},
                {"id":"list-5-7-3", "parentid":"list-5-7", "topic":"快速排序"},
                {"id":"list-5-7-4", "parentid":"list-5-7", "topic":"希尔排序"},
                {"id":"list-5-7-5", "parentid":"list-5-7", "topic":"系统方法"},
                /* 代码版本库 */
                {"id":"list-5-8-1", "parentid":"list-5-8", "topic":"svn"},
                {"id":"list-5-8-2", "parentid":"list-5-8", "topic":"git"},
                /* 项目的构建与部署 */
                {"id":"list-5-12-1", "parentid":"list-5-12", "topic":"fis3"},
                {"id":"list-5-12-2", "parentid":"list-5-12", "topic":"yeomen"},
                {"id":"list-5-12-3", "parentid":"list-5-12", "topic":"scrat"},
                {"id":"list-5-12-4", "parentid":"list-5-12", "topic":"modjs"},
                {"id":"list-5-12-5", "parentid":"list-5-12", "topic":"vuejs"},
                /* h5的移动开发 */
                {"id":"list-5-13-1", "parentid":"list-5-13", "topic":"phonegap"},
                {"id":"list-5-13-2", "parentid":"list-5-13", "topic":"cordova"},
                /* webapp */
                {"id":"list-5-15-1", "parentid":"list-5-15", "topic":"定位"},
                {"id":"list-5-15-2", "parentid":"list-5-15", "topic":"响应式开发"},
                {"id":"list-5-15-3", "parentid":"list-5-15", "topic":"webapp性能优化"},
                {"id":"list-5-15-4", "parentid":"list-5-15", "topic":"webapp开发调试"},
            /* h5游戏工程师 */
            {"id":"list-6-1", "parentid":"list-6", "topic":"html5游戏的概述"},
            {"id":"list-6-2", "parentid":"list-6", "topic":"DOM游戏的开发与入门"},
            {"id":"list-6-3", "parentid":"list-6", "topic":"用css3构建《纸牌记忆配对》"},
            {"id":"list-6-4", "parentid":"list-6", "topic":"用canvas构建游戏"},
            {"id":"list-6-5", "parentid":"list-6", "topic":"给游戏添加声音效果"},
            {"id":"list-6-6", "parentid":"list-6", "topic":"利用本地缓存保存游戏数据"},
            {"id":"list-6-7", "parentid":"list-6", "topic":"利用websocket构建多人游戏"},
            {"id":"list-6-8", "parentid":"list-6", "topic":"物理引擎"},
            {"id":"list-6-9", "parentid":"list-6", "topic":"粒子系统"},
            {"id":"list-6-10", "parentid":"list-6", "topic":"webGL"},
                /* html5游戏的概述 */
                {"id":"list-6-1-1", "parentid":"list-6-1", "topic":"探索h5游戏新功能"},
                {"id":"list-6-1-2", "parentid":"list-6-1", "topic":"探索css3新功能"},
                {"id":"list-6-1-3", "parentid":"list-6-1", "topic":"h5和css3新功能更多细节"},
                {"id":"list-6-1-4", "parentid":"list-6-1", "topic":"h5游戏的好处"},
                {"id":"list-6-1-5", "parentid":"list-6-1", "topic":"h5可以做跟多的事"},
                /* DOM游戏的开发与入门 */
                {"id":"list-6-2-1", "parentid":"list-6-2", "topic":"游戏开发的准备"},
                {"id":"list-6-2-2", "parentid":"list-6-2", "topic":"设置乒乓球游戏的元素"},
                {"id":"list-6-2-3", "parentid":"list-6-2", "topic":"获取游戏玩家的键盘输入以及同时输出"},
                {"id":"list-6-2-4", "parentid":"list-6-2", "topic":"物体的移动个碰撞检测"},
                /* 用css3构建《纸牌记忆配对》 */
                {"id":"list-6-3-1", "parentid":"list-6-3", "topic":"css3d基础和背面可见性"},
                {"id":"list-6-3-2", "parentid":"list-6-3", "topic":"给配对的游戏添加游戏逻辑"},
                {"id":"list-6-3-3", "parentid":"list-6-3", "topic":"在游戏中嵌入字体"},
                /* 用canvas构建游戏 */
                {"id":"list-6-4-1", "parentid":"list-6-4", "topic":"canvas简介"},
                {"id":"list-6-4-2", "parentid":"list-6-4", "topic":"canvas基础和api"},
                {"id":"list-6-4-3", "parentid":"list-6-4", "topic":"canvas渐变填充和高级技巧"},
                /* 给游戏添加声音效果 */
                {"id":"list-6-5-1", "parentid":"list-6-5", "topic":"给play添加声音按钮"},
                {"id":"list-6-5-2", "parentid":"list-6-5", "topic":"构建迷你钢琴游戏"},
                /* 利用本地缓存保存游戏数据 */
                {"id":"list-6-6-1", "parentid":"list-6-6", "topic":"利用h5保存本地缓存"},
                {"id":"list-6-6-2", "parentid":"list-6-6", "topic":"在本地缓存中保存对象"},
                {"id":"list-6-6-3", "parentid":"list-6-6", "topic":"突破游戏记录的绚丽效果"},
                /* 利用websocket构建多人游戏 */
                {"id":"list-6-7-1", "parentid":"list-6-7", "topic":"nodejs创建socket服务器"},
                {"id":"list-6-7-2", "parentid":"list-6-7", "topic":"使用websocket构建聊天室"},
                {"id":"list-6-7-3", "parentid":"list-6-7", "topic":"使用canvas和socket构建共享画板"},
                /* webGL */
                {"id":"list-6-10-1", "parentid":"list-6-10", "topic":"webGL起源"},
                {"id":"list-6-10-2", "parentid":"list-6-10", "topic":"webGL工作原理"},
                {"id":"list-6-10-3", "parentid":"list-6-10", "topic":"库"},
            /* windows&linux基础 */
            {"id":"list-7-1", "parentid":"list-7", "topic":"用户的权限和用户组"},
            {"id":"list-7-2", "parentid":"list-7", "topic":"任务管理cpu和占用的kill进程"},
            {"id":"list-7-3", "parentid":"list-7", "topic":"定时任务"},
            {"id":"list-7-4", "parentid":"list-7", "topic":"shell和批处理命令"},
            {"id":"list-7-5", "parentid":"list-7", "topic":"命令的方式复制，修改，删除文件夹"},
            {"id":"list-7-6", "parentid":"list-7", "topic":"文件的增删改查权限"},
            {"id":"list-7-7", "parentid":"list-7", "topic":"远程连接主机"},
            {"id":"list-7-8", "parentid":"list-7", "topic":"windows&linux的互通开发samba"},
            /* 后端语言 */
            {"id":"list-8-1", "parentid":"list-8", "topic":"php"},
            {"id":"list-8-2", "parentid":"list-8", "topic":"nodejs"},
                /* nodejs */
                {"id":"list-8-2-1", "parentid":"list-8-2", "topic":"nodejs开发环境以及NPM"},
                {"id":"list-8-2-2", "parentid":"list-8-2", "topic":"基础的中间件和创建服务器"},
                {"id":"list-8-2-3", "parentid":"list-8-2", "topic":"nodejs io 和socekt"},
                {"id":"list-8-2-4", "parentid":"list-8-2", "topic":"nodejs 的框架experess"},
                {"id":"list-8-2-5", "parentid":"list-8-2", "topic":"进程以及日志管理"},
                {"id":"list-8-2-6", "parentid":"list-8-2", "topic":"开发基于rest的后天框架"},
                {"id":"list-8-2-7", "parentid":"list-8-2", "topic":"yog和yogurt开发nodejs项目"},
                {"id":"list-8-2-8", "parentid":"list-8-2", "topic":"node多核处理模块cluster"},
                {"id":"list-8-2-9", "parentid":"list-8-2", "topic":"sql基础以及mongodb"},
                {"id":"list-8-2-10", "parentid":"list-8-2", "topic":"连接sql和mongdb"},
                {"id":"list-8-2-11", "parentid":"list-8-2", "topic":"orm操作数据库"},
                {"id":"list-8-2-12", "parentid":"list-8-2", "topic":"基础三层模式下的留言本"},
            /* http协议 */
            {"id":"list-9-1", "parentid":"list-9", "topic":"基础架构和功能以及历史版本信息"},
            {"id":"list-9-2", "parentid":"list-9", "topic":"http通用请求头"},
            {"id":"list-9-3", "parentid":"list-9", "topic":"http状态码"},
            {"id":"list-9-4", "parentid":"list-9", "topic":"工作原理以及详细了解请求流程图"},
            /* 前端的明天 */
            {"id":"list-10-1", "parentid":"list-10", "topic":"html6"},
            {"id":"list-10-2", "parentid":"list-10", "topic":"ECMAScript6"},
            {"id":"list-10-3", "parentid":"list-10", "topic":"css4"},
                /* html6 */
                {"id":"list-10-1-1", "parentid":"list-10-1", "topic":"命名空间里定义标签"},
                {"id":"list-10-1-2", "parentid":"list-10-1", "topic":"单标签和双标签"},
                /* ECMAScript6 */
                {"id":"list-10-2-1", "parentid":"list-10-2", "topic":"let和const命令"},
                {"id":"list-10-2-2", "parentid":"list-10-2", "topic":"变量的解构赋值"},
                {"id":"list-10-2-3", "parentid":"list-10-2", "topic":"字符串的扩展"},
                {"id":"list-10-2-4", "parentid":"list-10-2", "topic":"数值的扩展"},
                {"id":"list-10-2-5", "parentid":"list-10-2", "topic":"对象的扩展"},
                {"id":"list-10-2-6", "parentid":"list-10-2", "topic":"函数的扩展"},
                {"id":"list-10-2-7", "parentid":"list-10-2", "topic":"set和map的数据结构"},
                {"id":"list-10-2-8", "parentid":"list-10-2", "topic":"iterator和for..of循环"},
                {"id":"list-10-2-9", "parentid":"list-10-2", "topic":"cenerator函数"},
                {"id":"list-10-2-10", "parentid":"list-10-2", "topic":"promise对象"},
                {"id":"list-10-2-11", "parentid":"list-10-2", "topic":"class和module"},
                {"id":"list-10-2-12", "parentid":"list-10-2", "topic":"编程风格"},
                /* css4 */
                {"id":"list-10-3-1", "parentid":"list-10-3", "topic":"父选择器：$E>F"},
                {"id":"list-10-3-2", "parentid":"list-10-3", "topic":"链接地址的伪类"},
                {"id":"list-10-3-3", "parentid":"list-10-3", "topic":"语言的伪类"},
                {"id":"list-10-3-4", "parentid":"list-10-3", "topic":"综合案例"},


        ]
    };
    var jm = jsMind.show(info,data);
    var array=['list-1','list-2','list-3','list-4','list-5','list-6','list-7','list-8','list-9','list-10'
                ,'list-1-3','list-1-3-1','list-1-3-2','list-2-1','list-2-2','list-2-3','list-2-4','list-2-5'
                ];
    for(var i=0;i<array.length;i++){
        jm.collapse_node(array[i])
    }
})();